### ISSUE TITLE
Document time should use the correct zero point

### ISSUE THREAD

**Issue by steveblock** [web-animations/web-animations-js-legacy#101]
Currently, the zero point of document time is when the polyfill loads. We agreed at the recent face-to-face that the zero point should be at document load time (at least for the default group / default timeline). See https://etherpad.mozilla.org/ep/pad/view/ro.e9QRyeowiu6/latest

Presumably we'll use window.performance.loadEventStart. See http://www.w3.org/TR/navigation-timing/#dom-performancetiming-loadstart

**Comment by birtles** [comment]
Yes, that's actually defined under section 6.1: https://dvcs.w3.org/hg/FXTF/raw-file/separate-api/web-anim/index.html

**Comment by steveblock** [comment]
> Yes, that's actually defined under section 6.1
> Thanks Brian. I'll also update the patch to reflect the behaviour when the timeline is not started,

**Comment by steveblock** [comment]
Fixed with https://github.com/web-animations/web-animations-js/pull/102
