### ISSUE TITLE
Consider using performance timing with prefixed RAF implementation

### ISSUE THREAD

**Issue by steveblock** [web-animations/web-animations-js-legacy#117]
Currently we don't use performance timing, even when it's available, unless the RAF implementation is unprefixed. This is due to concerns that prefixed RAF implementations use the wrong time origin.

See https://github.com/web-animations/web-animations-js/commit/8495f0128c91130df87883f7d3a77612a3cf5ac5

**Comment by dstoc** [comment]
I don't think this matters since the only place requestAnimationFrame is still prefixed is in Safari, and performance timing is not available there.

**Comment by dstoc** [comment]
Or not, still prefixed in Firefox.

**Comment by dstoc** [comment]
Fixed in 3a59fe62
