### ISSUE TITLE
Animations containing % transforms fail on Chrome 25

### ISSUE THREAD

**Issue by sorvell** [web-animations/web-animations-js-legacy#130]
new Animation(target,
  {'-webkit-transform': ['translate3d(0,0,0)', 'translate3d(100%,0,0)'],
  1
);

The above animation fails on Chrome 25 but works on Canary. I notice that -webkit-calc is used to generate intermediate values for this animation. This appears not to be supported.

This problem is also evident in test-transform-units.html which fails silently. Notice, for example, the top row left and right squares. These do not animate properly but do have the correct end state.

**Comment by dstoc** [comment]
The underlying problem is that calc doesn't work in transforms in older versions of webkit (prior to https://bugs.webkit.org/show_bug.cgi?id=16662). We use calc when dealing with different unit types, in this case we could probably avoid it by treating 0 as 0%.

**Comment by shans** [comment]
Doug, Steve and I should talk about whether a weakly typed zero would be useful. I suspect there may be some minor performance gains as well as a little more permissiveness of input; but conversely this issue basically goes away as of the next Chrome version.

In the short term, you can work around this issue by using translate3d(0%, 0, 0) as the from value.

**Comment by sorvell** [comment]
That workaround is very helpful. Thanks.

**Comment by dstoc** [comment]
Chrome 25 is ancient history now :)
