### ISSUE TITLE
Consider making animating 'transform' property work cross-browser

### ISSUE THREAD

**Issue by sorvell** [web-animations/web-animations-js-legacy#133]
It would be extremely helpful to have animations using the 'transform' property work cross-browser. 

Rather than requiring users to duplicate animation values for -moz-transform, -webkit-transform, -ms-transform, transform, etc., the polyfill could feature detect the client's actual transform property and normalize an animation using the standard 'transform' property to the supported property name.

**Comment by birtles** [comment]
-moz-transform is no longer needed as of Firefox 16. We want to encourage authors to not use prefixes in future so I think it would be best if the polyfill only accepted 'transform' and translated that into '-webkit-transform' and '-ms-transform' when needed.

**Comment by dstoc** [comment]
Fixed in ec44a2b.
