### ISSUE TITLE
Do something with TimedItem.changePlaybackRate()

### ISSUE THREAD

**Issue by steveblock** [web-animations/web-animations-js-legacy#135]
The polyfill currently provides TimedItem.changePlaybackRate(), which updates TimedItem.timing.playbackRate and seeks so as to preserve the current playback position. The method is not in the spec.

We should decide how we want to expose this functionality and then make sure the spec and polyfill match up.

We probably can't do this until we've resolved how to expose supplied and calculates timing parameters. See https://github.com/web-animations/web-animations-js/issues/134

**Comment by birtles** [comment]
It's not needed on TimedItem anymore and should be removed. You can't change the playbackRate of a TimedItem and keep the current position. That's just not how the model works. It's the same with duration and other properties. If you want to change the run-time playback rate then you do that on the player and the position is preserved.

**Comment by steveblock** [comment]
Agreed.

I can remove it from TimedItem now, but I don't want to re-implement it on Player until we've reached a resolution on TimedItem.specified, TimedItem.getComputedTiming() etc.

**Comment by birtles** [comment]
It's much easier to implement on Player since it's a lot simpler there.
The discussion about specified / computed timing should be entirely orthogonal. Neither will re-introduce changePlaybackRate to TimedItem.

**Comment by steveblock** [comment]
Fixed with https://github.com/web-animations/web-animations-js/pull/155
