### ISSUE TITLE
Remove Player.cancel()

### ISSUE THREAD

**Issue by steveblock** [web-animations/web-animations-js-legacy#136]
We decided to remove this as it's just syntactic sugar for 'Player.source = null;'. See agenda item 5 of https://etherpad.mozilla.org/ep/pad/view/ro.gsZ7DnSJB9X/latest

We need to remove this from both the spec and polyfill.

**Comment by steveblock** [comment]
Removed from polyfill with https://github.com/steveblock/web-animations-js/commit/27d074ccf46c0dfa3d1ed9ed70908a3d1831db1b

Over to Brian for spec update.

**Comment by birtles** [comment]
It's already gone from the spec.
