### ISSUE TITLE
Need to call into timedItem parameter when timeline.play() is called

### ISSUE THREAD

**Issue by shans** [web-animations/web-animations-js-legacy#158]
Currently we don't update timedItems when we call play and pass them as a parameter. This means that:
- currentTime is incorrect until a raf cycle
- media doesn't update pause state, etc. until a raf cycle

We should include an update step on timedItems when play is called to ensure the timeline is immediately placed into a consistent state.

**Comment by steveblock** [comment]
I'll look into this.
