### ISSUE TITLE
Section 12.1 of spec includes spurious reference to time drift

### ISSUE THREAD

**Issue by steveblock** [web-animations/web-animations-js-legacy#163]
TimedItem is no longer seekable, so has no concept of a time drift.

**Comment by birtles** [comment]
Hi, thanks for pointing this out. Can you please file spec bugs in the w3c bugzilla? (Or just tell me on IRC and I'll add them to my todo list.) Thanks!

**Comment by steveblock** [comment]
Sure, can you provide a link to the W3C bugzilla? Also, if we're going to file spec bugs there, we should remove the 'spec' tag here.

**Comment by steveblock** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=21357
