### ISSUE TITLE
Section 8.2 of spec defines local time incorrectly 

### ISSUE THREAD

**Issue by steveblock** [web-animations/web-animations-js-legacy#164]
The spec states that the local time of a timed item is the sum of the timed item's inherited time and its start time. It should be the inherited time less the start time. Note that the example is correct.

**Comment by birtles** [comment]
Please file in w3c bugzilla.
https://www.w3.org/Bugs/Public/enter_bug.cgi?product=FXTF

**Comment by steveblock** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=21356
