### ISSUE TITLE
How do I specify an accumulate operation?

### ISSUE THREAD

**Issue by morethanreal** [web-animations/web-animations-js-legacy#184]
How do I specify an accumulate operation?

```
new Animation(target, {left: ["0px","50px"], accumulateOperation:"accumulate"})
```

doesn't seem to work.

**Comment by shans** [comment]
Accumulate operations aren't supported yet, but it looks like you actually just want to specify the operation here.

Accumulate operations control how an animation interacts with itself over multiple iterations - for example:
new Animation(target, {left: ["0px", "50px"], accumulateOperation: "accumulate"}, {iterationCount: 4, duration: 0.5})
is intended to animate the target's left property from 0px to 200px over 2 seconds.

Operations control how an animation interacts with other animations and the underlying property values - for example:
new Animation(target, {left: ["0px", "50px"], operation: "add"}, 0.5)
should add 50px to the existing left value of target over 0.5 seconds.

If I'm wrong and you actually do want accumulate operations then let us know and we'll increase the priority for implementing them.

**Comment by morethanreal** [comment]
Ah, I see. I don't need accumulate operations specifically and am just experimenting with what's available in the spec, so I can make sure they're implemented in the declarative component.
