### ISSUE TITLE
operation:"add" doesn't work if the previous player.source is set to null

### ISSUE THREAD

**Issue by morethanreal** [web-animations/web-animations-js-legacy#186]
In [this example](https://gist.github.com/anonymous/7eb8dedc25068b66f0e8) I play an animation with operation:"replace" and then one with operation:"add":

```
var replace = new Animation(target, {left: ["0px","50px"]}, 0.2);
var player = document.timeline.play(replace);

setTimeout(function() {
// works if the next line is commented
player.source = null;
var add = new Animation(target, {left: ["0px", "100px"], operation: "add"}, 0.2);
document.timeline.play(add);
```

If I set the first animation's player.source to null, the second animation with operation:"add" doesn't work. If I don't, it works.

**Comment by dstoc** [comment]
Looks like this was fixed at some point: http://jsfiddle.net/quJFE/
