### ISSUE TITLE
Pausing an animation before adding it to a group can cause the animation not to play with the group

### ISSUE THREAD

**Issue by sorvell** [web-animations/web-animations-js-legacy#31]
Given:

anim1 = new Animation(/\* ... */);
anim1.pause();
anim = new SeqGroup([anim1]); 

Expected result: anim1 will play when anim is played.
Actual result: anim1 never appears to play.

See smoke test here: https://github.com/sorvell/web-animations-js/blob/master/smoketests/test-pause-then-group.html

**Comment by dstoc** [comment]
Obsolete. Individual timed items may no longer be paused.
