### ISSUE TITLE
Reversing an animation after creating it makes it not initially play

### ISSUE THREAD

**Issue by sorvell** [web-animations/web-animations-js-legacy#32]
Given:

anim = new Animation(/\* ... */);
anim.reverse();

Expected result: anim plays in reverse
Actual result: anim acts as if it's initially paused. Calling play does play the animation in reverse as expected.

See: https://github.com/sorvell/web-animations-js/blob/master/smoketests/test-reverse.html

**Comment by steveblock** [comment]
Since we switched to the Player model, Animations are no longer reversable, so I think this bug is redundant.

Note that Player has a writable playbackRate property, but no reverse() method. Please re-open if you see similar problems there.
