### ISSUE TITLE
Tests which are reliable when run in Chrome directly are flaky under run_tests.py

### ISSUE THREAD

**Issue by steveblock** [web-animations/web-animations-js-legacy#322]
An example is the tests for MediaReference in https://github.com/web-animations/web-animations-js/pull/316

**Comment by steveblock** [comment]
Note that this test case is also subject to https://github.com/web-animations/web-animations-js/issues/324 so the summary does not always show the failure!

**Comment by steveblock** [comment]
Tim, any idea how involved the fix for this might be? If it'll take some time to fix, I'll land https://github.com/web-animations/web-animations-js/pull/316 now with the test temporarily disabled.

**Comment by mithro** [comment]
I'll look at this on Monday, really want to dig into the problem here as I've yet to be able to reproduce this problem locally....

**Comment by mithro** [comment]
This turned out to be the difference between loading the file from local disk and loading it from a HTTP server.
- Local (IE on disk) video files are seekable
- Remote (IE requested via HTTP) video files are not seekable

Starting at line 1292

``` javascript
_isSeekableUnscaledTime: function(time) {
   var seekTime = time * this._media.defaultPlaybackRate;
   var ranges = this._media.seekable;
   for (var i = 0; i < ranges.length; i++) {
     if (seekTime >= ranges.start(i) && seekTime <= ranges.end(i)) {
       return true;
     }
   }
   return false;
 },
```

When loaded of disk

``` javascript
> this._media.seekable
TimeRanges {length: 1, start: function, end: function}
```

When loaded from network

``` javascript
this._media.seekable
TimeRanges {length: 0, start: function, end: function}
```

**Comment by steveblock** [comment]
It looks like this is a bug in Chrome. See https://github.com/web-animations/web-animations-js/pull/316#issuecomment-20329158
