### ISSUE TITLE
Test runner sometimes fails to report failures

### ISSUE THREAD

**Issue by steveblock** [web-animations/web-animations-js-legacy#324]
In some cases, the summary at http://localhost:52868/test/test-runner.html? fails to list an assert which is shown as failing in the test itself. A minimised test case which demonstrates this is ...

timing_test(function() {
 at(1.0, function() {
   assert_true(false);
 });
}, "Obvious failure");

**Comment by mithro** [comment]
This issue was fixed in https://github.com/web-animations/web-animations-js/pull/308
