### ISSUE TITLE
Calling reverse then pause on a group can result in the group not properly playing

### ISSUE THREAD

**Issue by sorvell** [web-animations/web-animations-js-legacy#33]
Given:

anim1 = new Animation(/\* ... */);
anim = new SeqGroup([anim1]);
anim.reverse();
anim.pause();

Expected result: anim is paused and if anim.play() is called, the group will play in reverse.
Actual result: the group does not play, but if anim.play() is called again, it plays as expected.

See: https://github.com/sorvell/web-animations-js/blob/master/smoketests/test-reverse-group.html

**Comment by dstoc** [comment]
Obsolete issue.
