### ISSUE TITLE
onstart event not fired if there is no startDelay

### ISSUE THREAD

**Issue by morethanreal** [web-animations/web-animations-js-legacy#372]

**Comment by shans** [comment]
onstart events are definitely _sometimes_ fired if there is no startDelay - see for example all the tests in https://github.com/web-animations/web-animations-js/blob/master/test/testcases/test-events.html.

Can you give more details of the case that is failing?

**Comment by morethanreal** [comment]
Seems like it fails if I create the animation and then play it in a setTimeout: http://jsbin.com/azokay/1/edit

**Comment by morethanreal** [comment]
Ping? Polymer has a few use cases when a reliable onstart event would be very useful.

**Comment by shans** [comment]
Fixed by #508
