### ISSUE TITLE
Should "offfset" be considered good naming?

### ISSUE THREAD

**Issue by martinheidegger** [web-animations/web-animations-js-legacy#383]
"offset" as used in web-animations to indicate that some animation should be run at a time-offset is mixed with other properties like "left" or "marginTop" etc. many of those properties indicate a geometric space in which "offset" as a word also has a common meaning and is often used.

To make this clearer to the reader and easier to learn I am wondering if a property like "timeOffset" might be better.

**Comment by birtles** [comment]
Added to the agenda for tomorrow's meeting: https://etherpad.mozilla.org/PoetD3BlFl

**Comment by dstoc** [comment]
Marked as issue in spec.
