### ISSUE TITLE
Can't set style attributes after running an animation

### ISSUE THREAD

**Issue by morethanreal** [web-animations/web-animations-js-legacy#490]
Gist: https://gist.github.com/morethanreal/7223246

If you run an animation before setting the style attribute, the style attribute has no effect.

**Comment by robmcmackin** [comment]
This is also giving me trouble if you ever figured out how to remedy it?

**Comment by dstoc** [comment]
Is this just because the animation has forwards fill by default? Does setting fill: 'none' solve the problem?

**Comment by robmcmackin** [comment]
Yes Thanks

On Thu, Nov 28, 2013 at 2:54 AM, Douglas Stockwell <notifications@github.com

**Comment by morethanreal** [comment]
I can still repro the original issue. jsbin: http://jsbin.com/iPAmUJEy/2/edit

If you tap the "animate" button first to run an Animation (with fill: 'none') and then tap the "-webkit-transform" button to apply a style, the transform has no effect.

**Comment by dstoc** [comment]
@morethanreal currently I think it should work if you set element.style.webkitTransform. @alancutter says that element.style.setPropertyValue('-webkit-transform', value) should work too.

**Comment by alancutter** [comment]
This kind of property access on style objects is outside specification [1] and is not supported across all major browsers.
Without a good reason for supporting this kind of behaviour it's better if the polyfill does not provide it.

[1] http://dev.w3.org/csswg/cssom/#the-cssstyledeclaration-interface
