### ISSUE TITLE
Polyfill not working in Canary

### ISSUE THREAD

**Issue by morethanreal** [web-animations/web-animations-js-legacy#556]
The polyfill is not working in today's Chrome Canary (34.0.1847.3 (Official Build 252028) canary) with --enable-experimental-web-platform-features. It works fine without --enable-experimental-web-platform-features and I suspect it has to do with Element.animate landing.

gist: https://gist.github.com/morethanreal/9104830

**Comment by shans** [comment]
document.timeline.play isn't being replaced correctly by the polyfill (we just started providing a native implementation of this). Fix pending.

**Comment by alancutter** [comment]
We really ought to have an experimental Chrome target for Travis to catch these in future.
