### ISSUE TITLE
Finish event on a reversed animation

### ISSUE THREAD

**Issue by douglasduteil** [web-animations/web-animations-js-legacy#583]
Hi
I'm trying to get a callback at the end of a reversed running animation.  

Looking at the spec I tryed using the `AnimationPlayer#reverse` function:
- setting a callback to the `TimedItem#onend` EventHandler but it's not called at the end on the reverse.
- setting a callback to the [`AnimationPlayer#onfinish`](http://dev.w3.org/fxtf/web-animations/#widl-AnimationPlayer-onfinish) EventHandler but it not seems to be implemented yet.  

I end up hacking the `Timing#direction` and the `AnimationPlayer#currentTime` to get a `TimedItem#onend` event with something like this : 

``` js
var direction = player.source.timing.direction;
player.source.timing.direction = 
    direction === 'normal' ? 'reverse' : 'normal';

player.currentTime = player.source.endTime - player.source.localTime;
```

Here is my [demo playground](http://jsbin.com/lutof/1)
after playing an animation, click on one of the 'reverse' button and see the callback result in the log  

What you think ? What's the _right_ way to do it ?

**Comment by dstoc** [comment]
The Player 'finish' event will be implemented soon, @alancutter is going to look at it today. It should work for your use case of a reversed player or animation.

The events on TimedItem will be deprecated, they should already have been removed from the spec.

**Comment by douglasduteil** [comment]
OK Cool @dstockwell 
I can't wait to use it !
Thanks for your work :)
