### ISSUE TITLE
CSS Filters WebAnimation Support

### ISSUE THREAD

**Issue by douglasduteil** [web-animations/web-animations-js-legacy#632]
### Are the `CSS filters` animations supported ?

---

I tryed a basic CSS Filter hue rotation animation : 

> in CSS
> 
> ``` css
> #cssHueAnimated {
>   animation: hue 30s infinite;
> }
> 
> @keyframes hue {
>   from {
>     -webkit-filter: hue-rotate(0deg);
>   }
> 
>  to {
>     -webkit-filter: hue-rotate(360deg);
>   }
> }
> ```

Like so  : 

> in JS
> 
> ``` js
> function Hue(elem) {
>   var keyframes = [
>     {'-webkit-filter': 'hue-rotate(0deg)'},
>     {'-webkit-filter': 'hue-rotate(360deg)'}
>   ];
> 
>  return elem.animate(keyframes, {duration: 30000, iterations: Infinity});
> }
> ```

But the result is not the same.
The Web Animation version is just brutally switching between `-webkit-filter: hue-rotate(0deg);` and  `-webkit-filter: hue-rotate(360deg);`. Normal ?

[Demo](http://embed.plnkr.co/rbAE6V/preview)

**Comment by dstoc** [comment]
It's not implemented yet, you can see the list of what is currently supported here:
https://github.com/web-animations/web-animations-js/blob/d6361cb60dc42e553048e40f47c9ddb8b3f54005/web-animations.js#L4388

**Comment by douglasduteil** [comment]
Ok thanks

Do you mind if I contribuate to the [web-animations-demos](https://github.com/web-animations/web-animations-demos) ?

**Comment by dstoc** [comment]
> Do you mind if I contribuate to the web-animations-demos ?

That would be great! We're in the process of switching to a new codebase (see https://github.com/web-animations/web-animations-next), there's a small summary of the status here: https://github.com/web-animations/web-animations-js/issues/627#issuecomment-50601503
