### ISSUE TITLE
Several scripts are missing license header

### ISSUE THREAD

**Issue by dzhioev** [web-animations/web-animations-js-legacy#641]
Hello,
I'm adding a copy of web-animations-js to Chromium codebase, and I have a little problem.
We have a rule that every third-party file containing a source code should have a licence header. The script that enforces this rule has detected that several files in the web-animations-js repository don't have such header:

'.travis-setup.sh'
'run-lint.sh'
'run-tests.sh'
'.travis-run.sh'
'tools/python/run-tests.py'
'tools/python/setup.sh'
'tools/android/config.sh'
'tools/android/stop.sh'
'tools/android/setup.sh'
'run-tests-android.sh'

Could you please add an license header to these files?

**Comment by alancutter** [comment]
These files are probably of little use to you for embedding web-animation-js in Chromium as they're purely Javascript testing infrastructure code. I'd just remove them as part of porting the project across.

As a side note; all work on the Web Animations polyfill has moved on to https://github.com/web-animations/web-animations-next so this repository won't see much change in the near future. You should feel free to make changes on your own fork of the project without fear of falling behind tip-of-tree.
