### ISSUE TITLE
Animation starting time pausing problems at time 0

### ISSUE THREAD

**Issue by StephMc** [web-animations/web-animations-js-legacy#80]
In the code below #a is lightsteelblue instead of red when paused at time 0.

<style>
.anim {
  width: 100px;
  height: 100px;
  background-color: lightsteelblue;
}
</style>

<div id="a" class="anim"></div>

var foo = new Animation(document.querySelector("#a"), {"background-color": ["red", "green"]}, 2);
foo.pause();

**Comment by steveblock** [comment]
I have a fix at https://github.com/web-animations/web-animations-js/pull/82

**Comment by SHeimlich** [comment]
This seems to still be broken with the step functionality.  Running a ref test to a CSS3 element with the same animation failed.

**Comment by steveblock** [comment]
Sarah, do you mean you still see the bug, even with #82 merged? If so, please re-open.
